version: '3'

services:
  nginx:
    image: nginx:stable-alpine
    build:
      context: ./docker/nginx
    volumes:
      - ./volumes/build/faithwork-api:/symfony
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    container_name: nginx
    restart: always
    ports:
      - "8081:80"
    depends_on:
      - db
    command: docker exec php-cli php bin/console doctrine:migrations:migrate

  php-fpm:
    build:
      context: ./docker/php-fpm
    volumes:
      - ./volumes/build/faithwork-api:/symfony
    container_name: php-fpm
    depends_on:
      - db

  php-cli:
    build:
      context: ./docker/php-cli
    volumes:
      - ./volumes/build/faithwork-api:/symfony
    command: composer install
    container_name: faithwork-php-cli

  db:
    image: postgres:latest
    container_name: db
    environment:
      POSTGRES_USER: postgres_user
      POSTGRES_PASSWORD: postgres_password
      POSTGRES_DB: postgres_db
    ports:
      - "5432:5432"

volumes:
  db-data:
