services:
  # PHP-FPM Service
  php-fpm:
    container_name: php-fpm
    build:
      context: .
      dockerfile: ./host/php-fpm/Dockerfile
    volumes:
    # Mounts the local 'app' directory to the container's Nginx root
      - ./app/faithwork-api:/var/www/html  

  # NGINX Service
  faithwork-api:
    container_name: faithwork_api
    build:
      context: .
      dockerfile: ./host/faithwork-api/Dockerfile
    volumes:
    # Mountlocal 'app' directory to the Nginx root
      - ./app/faithwork-api:/var/www/html 
    ports:
      - "8081:80"
    depends_on:
      - php-fpm  # Depends on the PHP-FPM service
      - mysql-db

  # Faithwork-Web Service
  faithwork-web:
    container_name: faithwork_web
    build:
      context: .
      dockerfile: ./host/faithwork-web/Dockerfile
    ports:
      - "8080:80"

# MySQL Database Service
  mysql-db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: faithwork
      MYSQL_USER: fw_user
      MYSQL_PASSWORD: password
    ports:
    # Maps port 3306 on the host to port 3306 on the MySQL container
      - "3306:3306" 

# PHPMyAdmin Service
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
    # Links the PHPMyAdmin service to the MySQL database service
      - mysql-db 
    ports:
      - "8082:80" 
    environment:
      PMA_HOST: mysql-db
      # Use MySQL root password for PHPMyAdmin
      MYSQL_ROOT_PASSWORD: password 
    depends_on:
      - mysql-db