# Используем Node.js для сборки Vue.js приложения
FROM node:lts-alpine as build-stage
WORKDIR /app
COPY ./app/faithwork-web/package*.json ./
RUN npm install
COPY ./app/faithwork-web .
RUN npm run build

# Используем Nginx для статического хостинга
FROM nginx:stable-alpine as production-stage
COPY --from=build-stage /app/dist /usr/share/nginx/html

# Копируем конфигурацию Nginx
COPY ./host/faithwork-web/nginx.conf /etc/nginx/nginx.conf

# Экспонируем порт 80
EXPOSE 80

# Запускаем Nginx
CMD ["nginx", "-g", "daemon off;"]